"""empty message

Revision ID: 1f12cdac6639
Revises: 074b19058e8d
Create Date: 2023-05-14 01:41:01.987170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f12cdac6639'
down_revision = '074b19058e8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
